version: "3.8"

services:
  app:
    build: .
    ports:
      - "3005:3005"
    environment:
      - PORT=3005
      - MONGO_URI=mongodb://mongo:27017/tododb # Not used yet, but good practice
    depends_on:
      - mongo
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
