apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: nasirhayat028/todo-node-app:v1
        ports:
        - containerPort: 3005
        