services:
  web:
    ports:
      - "4000:3000"   # override: expose app on port 4000 instead of 3000
    environment:
      - GREETING=Hello from override!
    volumes:
      - ./logs:/app/logs  # optional: simulate writing logs to host
